name: Daily Exchange Rate Update

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-exchange-rate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 PyGithub

      - name: Run scraper
        run: python scraper.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: "yourusername/exchange-rate-repo"

      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add exchange_rate.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Updated exchange rate"
          git push
